version: '3.7'

services:
  app:
    build:
      args:
        user: seguro
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - app.env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    image: analizador:1.0
    restart: always
    container_name: app-A
    volumes:
      - ./app/proyectoPrograSegura:/app
    depends_on:
      - bd
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024M"

    
  bd:
    image: mariadb:10.8.3
    container_name: bd-A
    restart: always
    env_file:
      - bd.env
    environment:
      MYSQL_DATABASE: analizador
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024M"

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/certs:/tmp
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/proyectoPrograSegura/static:/static
    depends_on:
      - app
    ports:
      - 8000:80
      - 4343:443
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1024M"
