# Generated by Django 3.2.13 on 2022-06-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_auto_20220607_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_usuarios',
            name='token_telegram',
            field=models.CharField(default='', max_length=50),
        ),
    ]
