FROM python:3.9
RUN mkdir /identifica_archivos_txt
WORKDIR /identifica_archivos_txt
RUN mkdir /entorno_ejercicio
ADD inicializacion.sh /identifica_archivos_txt
ADD parametros.sh /identifica_archivos_txt
ADD final.sh /identifica_archivos_txt
RUN chmod +x inicializacion.sh
RUN chmod +x parametros.sh
RUN chmod +x final.sh
RUN useradd entorno -s /bin/bash
RUN chown -R entorno /identifica_archivos_txt
RUN chown -R entorno /entorno_ejercicio
RUN chmod -R 700 /identifica_archivos_txt
RUN chmod -R 700 /entorno_ejercicio
USER entorno
RUN /bin/bash -c "/identifica_archivos_txt/inicializacion.sh /entorno_ejercicio/"

