# Generated by Django 3.2.13 on 2022-05-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_usuarios',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='registro_usuarios',
            name='usuario',
            field=models.CharField(default='', max_length=20),
        ),
    ]
