# Generated by Django 3.2.12 on 2022-06-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_alter_registro_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_usuarios',
            options={'ordering': ['-id']},
        ),
    ]
