# Generated by Django 3.2.13 on 2022-06-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_auto_20220602_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_usuarios',
            options={},
        ),
        migrations.AddField(
            model_name='registro_usuarios',
            name='chat_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registro_usuarios',
            name='token_telegram',
            field=models.CharField(default='', max_length=20),
        ),
    ]
