# Generated by Django 4.0.1 on 2022-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0008_alter_registro_usuarios_token_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('token_telegram', models.CharField(default='', max_length=50)),
                ('chat_id', models.CharField(default='', max_length=20)),
                ('tipo_usuario', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('token_telegram', models.CharField(default='', max_length=50)),
                ('chat_id', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='registro_usuarios',
            name='tipo_usuario',
            field=models.CharField(default='', max_length=15),
        ),
    ]
