# Generated by Django 4.0.1 on 2022-06-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0009_grupo_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='id_grupo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id_usuario',
            field=models.BigIntegerField(),
        ),
    ]
