# Generated by Django 4.0.1 on 2022-06-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0010_alter_tarea_id_grupo_alter_tarea_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='entregadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField()),
                ('calificacion', models.IntegerField()),
            ],
        ),
    ]
