# Generated by Django 4.0.1 on 2022-06-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0009_alumnos_maestros_registro_usuarios_tipo_usuario'),
        ('modelo', '0011_entregadas'),
    ]

    operations = [
    ]
