# Generated by Django 4.0.1 on 2022-06-29 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0012_merge_20220628_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='uploadedFile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='tareas-de-alumnos/'),
            preserve_default=False,
        ),
    ]
