# Generated by Django 4.0.1 on 2022-06-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0012_merge_20220628_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='modelo.grupo'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='maestros',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='maestros',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='modelo.grupo'),
        ),
        migrations.AddField(
            model_name='maestros',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro_usuarios',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='modelo.grupo'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='modelo.grupo'),
        ),
    ]
