# Generated by Django 4.0.1 on 2022-06-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0013_alumnos_apellidos_alumnos_grupo_alumnos_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='id_grupo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='id_usuario',
        ),
    ]
