# Generated by Django 4.0.1 on 2022-06-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0014_remove_tarea_id_grupo_remove_tarea_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_usuarios',
            name='apellidos',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro_usuarios',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
