# Generated by Django 4.0.1 on 2022-06-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0016_entregada_rename_maestros_maestro_delete_entregadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='maestro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='modelo.maestro'),
        ),
    ]
