# Generated by Django 4.0.1 on 2022-06-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0017_tarea_maestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion1',
            field=models.CharField(default='', max_length=400),
        ),
    ]
