# Generated by Django 4.0.1 on 2022-06-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0018_tarea_descripcion1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='descripcion1',
            new_name='descripcion',
        ),
    ]
