# Generated by Django 4.0.1 on 2022-06-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0013_tarea_datetimeofupload_tarea_uploadedfile'),
        ('modelo', '0019_rename_descripcion1_tarea_descripcion'),
    ]

    operations = [
    ]
