# Generated by Django 4.0.1 on 2022-06-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0020_merge_20220629_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='dateTimeOfUpload',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='uploadedFile',
        ),
        migrations.AddField(
            model_name='entregada',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entregada',
            name='nombre',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='entregada',
            name='uploadedFile',
            field=models.FileField(default='', upload_to='tareas-de-alumnos/'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='script_comprobacion',
            field=models.FileField(default='', upload_to='tareas/'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='script_inicializacion',
            field=models.FileField(default='', upload_to='tareas/'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='script_parametros',
            field=models.FileField(default='', upload_to='tareas/'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(default='', max_length=40),
        ),
    ]
