<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-06-30 00:49
=======
<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-06-29 23:34
=======
# Generated by Django 4.0.1 on 2022-06-29 21:32
>>>>>>> 6e5172489afddf82b7705c6dc7a94501b1a15c69
>>>>>>> 6cfa064c7e345ac48ac49fc4e0333524e86a41a5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0021_remove_tarea_datetimeofupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='script_comprobacion',
            field=models.FileField(default='', upload_to='media/tareas/'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='script_inicializacion',
            field=models.FileField(default='', upload_to='media/tareas/'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='script_parametros',
            field=models.FileField(default='', upload_to='media/tareas/'),
        ),
    ]
