# Generated by Django 4.0.1 on 2022-06-30 13:22

from django.db import migrations, models
import modelo.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0022_alter_tarea_script_comprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregada',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entregada',
            name='uploadedFile',
            field=models.FileField(default='', upload_to=modelo.models.directorio_tarea),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='script_comprobacion',
            field=models.FileField(default='', upload_to=modelo.models.directorio_archivo),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='script_inicializacion',
            field=models.FileField(default='', upload_to=modelo.models.directorio_archivo),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='script_parametros',
            field=models.FileField(default='', upload_to=modelo.models.directorio_archivo),
        ),
    ]
